name: clang_tidy

defaults:
  #if: "!contains(github.event.head_commit.message, 'skip ci')"  # SKIP
  run:
    # Use a bash shell so we can use the same syntax for environment variable
    # access regardless of the host operating system
    shell: bash -e -x {0}

on:
  # https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  PROJ_PFX_TARGET: c4core-
  PROJ_PFX_CMAKE: C4CORE_
  CMAKE_FLAGS:
  NUM_JOBS_BUILD: # 4


jobs:

  #----------------------------------------------------------------------------
  clang_tidy:
    if: always()
    continue-on-error: false
    runs-on: ubuntu-24.04
    container: ghcr.io/biojppm/c4core/ubuntu22.04:latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - std: 11
          clang: 18
          bt: Debug
          bits: 64
    env:
      STD: ${{matrix.std}}
      CXX_: ${{matrix.cxx}}
      BT: ${{matrix.bt}}
      BITLINKS: ${{matrix.bitlinks}}
      VG: ${{matrix.vg}}
      SAN: ${{matrix.san}}
      LINT: ${{matrix.lint}}
      OS: ${{matrix.os}}
    steps:
    - name: checkout (action + docker)
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - run: git config --system --add safe.directory '*'
    - name: install
      run: c4core-install clang++-${{matrix.clang}}
    - name: configure
      run: |
        cmake -S . -B build \
           -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
           -DCMAKE_CXX_COMPILER=clang++-${{matrix.clang}} \
           -DCMAKE_C_COMPILER=clang-${{matrix.clang}} \
           -DCLANG_TIDY=/usr/bin/clang-tidy-${{matrix.clang}} \
           -DCMAKE_BUILD_TYPE=${{matrix.bt}} \
           -DC4CORE_DEV=ON \
           -DC4CORE_VALGRIND=OFF \
           -DC4CORE_BUILD_TESTS=OFF \
           -DC4CORE_BUILD_BENCHMARKS=OFF \
           -DC4CORE_DBG=OFF
    - name: clang-tidy
      run: cmake --build build --target c4core-clang-tidy --verbose
